[build]
  publish = "public"

    [build.environment]
      HUGO_VERSION = "0.145.0"
      HUGO_ENV = "production"
      HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --baseURL https://tomoki.dev/ --gc --minify"

[context.deploy-preview]
  command = "hugo --baseURL ${DEPLOY_PRIME_URL} --gc --minify --buildDrafts"

[context.branch-deploy]
  command = "hugo --baseURL ${DEPLOY_PRIME_URL} --gc --minify"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
    debug = true
    srcdir = "."

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    preset = "desktop"
